### PR TITLE
verbose flag added.

### PR DESCRIPTION
**Pull request by Sandman83**
With this, a line break before a space could be achieved. Maybe you find it useful...

### CODE REVIEW

**Comment by randy3k** [comment]
Let me try to understand. What situations are you trying to fix?

**Comment by Sandman83** [comment]
Sorry, just close the pull request...
what I meant is something else, in line 71 and 75, adding a "+1" at the end of the line... to get a line break after the space and not before... 
I'm not yet very familiar with the pull request process, so... I make just another, after you close this one?

**Comment by randy3k** [comment]
You don't have to open a new pull request, you just have to overwrite your current master branch.

**Comment by randy3k** [comment]
By the way, why would have like to keep the trailing space at the end of the line?

**Comment by Sandman83** [comment]
Because it seems strange to me to keep it at the beginning of the next line... Either the same amount of spaces (other symbols) as the current line should be kept, or nothing. E. g.
```
/*
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut 
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam 
*/
```
or 
```
/*
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut 
    labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam 
*/
```
but not something, which is influenced by my own typing...

**Comment by randy3k** [comment]
Indeed, it is a bug. It doesn't appear in one-line comment, plain text or latex. Will fix it.

**Comment by randy3k** [comment]
The reason is [auto_indent](https://github.com/randy3k/AutoWrap/blob/9606ace8b1bfd4b3c4c287a774da7becb679b79e/autowrap.py#L149-L149) doesn't work in comment block.

**Comment by Sandman83** [comment]
ah.. ok.. strange... is this a Sublime bug?

**Comment by randy3k** [comment]
Maybe. Anyway I have added a workaround for comment block. 
https://github.com/randy3k/AutoWrap/blob/3e73decd1c253f5bb093a2721699a98b88140b7b/autowrap.py#L153-L153

**Comment by Sandman83** [comment]
Thanks a lot! Works like a charm :)

**Pull request closed without merging**
